Repository github/issue-metrics, pull requests merged in 2023-11, with the labels that each got.

#163 fix: #161 Incorrect output values in issue_metrics.json
  json_writer.py
  markdown_writer.py
  test_json_writer.py
Labels: bug

#164 feature: support median and 90 percentile in json format.
  json_writer.py
  test_json_writer.py
Labels: enhancement

#167 Add contributions invite message
  README.md
Labels: documentation
