Repository github/issue-metrics, pull requests merged in 2023-09, with the labels that each got.

#106 docs(readme): document how to ignore bots
  README.md
Labels: documentation

#113 update: Makefile, .pylintrc
  .pylintrc
  Makefile
Labels: infrastructure

#111 Feature: Ignore PR time spent as draft, measure PRs by merge time
  README.md
  issue_metrics.py
  test_time_to_first_response.py
  test_time_to_merge.py
  test_time_to_ready_for_review.py
  time_to_first_response.py
  time_to_merge.py
  time_to_ready_for_review.py
Labels: enhancement

#116 linting fixes
  test_time_to_merge.py
  test_time_to_ready_for_review.py
  time_to_merge.py
  time_to_ready_for_review.py
Labels: bug

#118 Create pull_request-template.md
  .github/pull_request-template.md
Labels: infrastructure

#123 Correct pip command name
  README.md
Labels: documentation

#121 Exclude bot's comment from "Time to first response"
  README.md
  test_time_to_first_response.py
  time_to_first_response.py
Labels: enhancement

#125 Documentation: Add required python version to docs and test deps.
  README.md
  requirements.txt
Labels: bug

#129 feat: add author column
  README.md
  classes.py
  issue_metrics.py
  json_writer.py
  markdown_writer.py
  test_issue_metrics.py
  test_json_writer.py
  test_labels.py
  test_markdown_writer.py
  test_time_to_answer.py
  test_time_to_close.py
  test_time_to_first_response.py
Labels: enhancement

#126 Restructure README.md
  README.md
Labels: documentation
