Repository github/issue-metrics, pull requests merged in 2023-10, with the labels that each got.

#135 Support python 3.12
  .github/workflows/python-package.yml
Labels: infrastructure

#137 Docs improvements in README.md
  README.md
Labels: documentation

#138 Add dev dependencies to requirements.txt
  requirements.txt
Labels: infrastructure

#139 docs: update README (take over #131)
  .gitignore
  README.md
  docs/assign-team-instead-of-individual.md
  docs/example-using-json-instead-markdown-output.md
  docs/example-workflows.md
  docs/local-usage-without-docker.md
  docs/measure-time.md
  docs/search-query.md
Labels: documentation

#140 Fix README collisions
  README.md
  docs/search-query.md
Labels: documentation

#127 Support more than one statistic for summarizing time lists
  issue_metrics.py
  labels.py
  markdown_writer.py
  requirements.txt
  test_issue_metrics.py
  test_labels.py
  test_markdown_writer.py
  test_time_to_answer.py
  test_time_to_close.py
  test_time_to_first_response.py
  time_to_answer.py
  time_to_close.py
  time_to_first_response.py
Labels: enhancement, infrastructure

#141 [docs] Add back references to footnotes
  README.md
Labels: documentation

#145 docs: add `Getting Started` section in README
  README.md
Labels: documentation

#147 remove sub-seconds from stats
  labels.py
  time_to_answer.py
  time_to_close.py
  time_to_first_response.py
Labels: bug

#149 [docs] Fixing duplicated start of code block
  README.md
Labels: documentation

#148 Split out the summary table into 2 tables
  .vscode/settings.json
  markdown_writer.py
  test_markdown_writer.py
Labels: enhancement

#153 Add screenshot of sample report to the README
  README.md
  docs/img/issue-metrics-sample-output.png
  docs/search-query.md
Labels: documentation

#157 always print the title and search query
  markdown_writer.py
  test_markdown_writer.py
Labels: enhancement
