Repository github/issue-metrics, pull requests merged in 2024-04, with the labels that each got.

#233 docs: add github issue templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  README.md
Labels: documentation

#206 First stab at figuring out the number of very active mentors
  README.md
  classes.py
  config.py
  issue_metrics.py
  json_writer.py
  markdown_writer.py
  most_active_mentors.py
  test_config.py
  test_issue_metrics.py
  test_json_writer.py
  test_markdown_writer.py
  test_most_active_mentors.py
Labels: enhancement

#239 fix: Performance fix to only measure statistics which are not hidden
  .github/scripts/env_vars_check.sh
  Makefile
  issue_metrics.py
  test_issue_metrics.py
Labels: bug

#241 fix: add config for jscpd linter
  .github/linters/.jscpd.json
  .gitignore
Labels: bug

#242 feat: automated releases and auto labelling
  .github/pull_request-template.md
  .github/release-drafter.yml
  .github/workflows/auto-labeler.yml
  .github/workflows/pr-title.yml
  .github/workflows/release-drafter.yml
  .github/workflows/release.yml
  CONTRIBUTING.md
Labels: enhancement

#244 fix: release container image build
  .github/workflows/release.yml
Labels: fix

#247 fix: container image name
  .github/pull_request_template.md
  .github/workflows/release.yml
Labels: fix

#253 chore(deps): update dependabot config to include pr prefixes
  .github/dependabot.yml
  requirements-test.txt
Labels: maintenance

#257 fix: use GitHub App token when authed with GitHub App
  .github/pull_request_template.md
  auth.py
  issue_metrics.py
  most_active_mentors.py
  test_auth.py
  test_issue_metrics.py
  test_most_active_mentors.py
Labels: fix

#261 fix: handle multiple repos in search query
  issue_metrics.py
  test_issue_metrics.py
Labels: fix
