Repository github/issue-metrics, pull requests merged in 2024-05, with the labels that each got.

#265 feat: Split markdown files when larger than max issue body size
  .github/linters/.flake8
  .gitignore
  README.md
  docs/dealing-with-large-issue-metrics.md
  issue_metrics.py
  markdown_helpers.py
  test_markdown_helpers.py
Labels: feature

#267 chore: add OSSF scorecard github action and README badge
  .github/workflows/auto-labeler.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/contributor_report.yaml
  .github/workflows/docker-image.yml
  .github/workflows/linter.yaml
  .github/workflows/major-version-updater.yml
  .github/workflows/pr-title.yml
  .github/workflows/python-package.yml
  .github/workflows/release.yml
  .github/workflows/scorecard.yml
  .github/workflows/stale.yaml
  README.md
Labels: maintenance

#273 chore: group dependabot dependency updates for minor/patch updates
  .github/dependabot.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/contributor_report.yaml
  .github/workflows/docker-image.yml
  .github/workflows/linter.yaml
  .github/workflows/major-version-updater.yml
  .github/workflows/pr-title.yml
  .github/workflows/python-package.yml
  .github/workflows/release.yml
  .github/workflows/scorecard.yml
Labels: maintenance, release

#276 chore: delete unneeded custom codeql GitHub Action
  .github/workflows/codeql-analysis.yml
Labels: maintenance

#266 feat: Avoid API Rate-Limiting
  issue_metrics.py
  test_issue_metrics.py
Labels: feature

#278 chore: Switch to weekly dep updates to reduce noise
  .github/dependabot.yml
Labels: maintenance

#283 fix: Negative time reported for "time label applied" measurement
  labels.py
  test_labels.py
Labels: fix, release

#285 fix: allow access to forked pull request labels for release
  .github/workflows/release.yml
Labels: fix

#296 ci: release when a new feature hits main
  .github/workflows/release.yml
Labels: automation

#297 chore: remove pull_request target if we already have pull_request_target
  .github/workflows/auto-labeler.yml
  .github/workflows/release.yml
  README.md
Labels: maintenance

#298 ci: Add Jeff to review new data releases
  .github/pull_request_template.md
Labels: automation
