Repository github/issue-metrics, pull requests merged in 2024-10, with the labels that each got.

#396 feat: add bypass to rate limiter
  README.md
  config.py
  issue_metrics.py
  test_config.py
  test_issue_metrics.py
Labels: release, feature

#405 fix: pass through report name, issue title, and search query when report is empty
  issue_metrics.py
  markdown_writer.py
  test_issue_metrics.py
Labels: fix, release

#407 refactor: Move search functions and tests to their own files
  issue_metrics.py
  search.py
  test_issue_metrics.py
  test_search.py
Labels: automation

#414 docs: rm stale inline docs
  issue_metrics.py
Labels: documentation

#418 feat: support github enterprise api
  .env-example
  README.md
  auth.py
  config.py
  discussions.py
  issue_metrics.py
  markdown_writer.py
  test_auth.py
  test_config.py
  test_discussions.py
  test_markdown_writer.py
Labels: release, feature
