Repository github/issue-metrics, pull requests merged in 2024-06, with the labels that each got.

#304 chore: add Jacob to pr reviews automatically
  .github/CODEOWNERS
Labels: maintenance

#305 chore: standardize github action types
  .github/workflows/auto-labeler.yml
  .github/workflows/linter.yaml
  .github/workflows/pr-title.yml
  .github/workflows/release.yml
  .github/workflows/scorecard.yml
  config.py
  test_config_get_bool.py
Labels: maintenance

#313 feat: Add option to hide Number of items closed metric
  .env-example
  README.md
  config.py
  issue_metrics.py
  markdown_writer.py
  test_config.py
  test_markdown_writer.py
Labels: feature

#315 chore: pin shas in Dockerfile
  Dockerfile
Labels: maintenance

#325 fix: catch error that occurs when ghost usre creates an event.
  time_to_ready_for_review.py
Labels: fix

#326 fix: Catch review comments with no valid user
  time_to_first_response.py
Labels: fix
