Repository github/issue-metrics, pull requests merged in 2024-09, with the labels that each got.

#371 fix: typo in README
  README.md
Labels: fix

#370 feat: add non-mentioning links option
  README.md
  config.py
  issue_metrics.py
  markdown_writer.py
  test_config.py
  test_markdown_writer.py
Labels: release, feature

#373 feat: REPORT_TITLE and OUTPUT_FILE environment variables
  .env-example
  README.md
  config.py
  issue_metrics.py
  json_writer.py
  markdown_writer.py
  test_config.py
  test_json_writer.py
  test_markdown_writer.py
Labels: release, feature

#375 fix: too many arguments to write_to_json
  issue_metrics.py
Labels: fix, release

#379 fix: Remove ignore_users authored items from markdown results
  README.md
  issue_metrics.py
  test_issue_metrics.py
Labels: fix, release

#382 fix: Remove more general part of duplicate actions permissions
  .github/workflows/major-version-updater.yml
Labels: fix

#385 docs: developer setup instructions to run codebase
  README.md
Labels: documentation

#387 docs: instructions on verifying token access to a repository
  README.md
  docs/verify-token-access-to-repository.md
Labels: documentation

#391 chore: use setup python to improve OSSF scorecard
  .github/workflows/linter.yaml
Labels: maintenance

#392 docs: Add OSSF Best Practices Badge
  README.md
Labels: documentation

#393 chore: Remove unneeded pip install
  .github/workflows/python-package.yml
Labels: maintenance
