Repository github/issue-metrics, pull requests merged in 2025-01, with the labels that each got.

#451 feat: move to reusable workflows
  .github/release-drafter.yml
  .github/workflows/auto-labeler.yml
  .github/workflows/major-version-updater.yml
  .github/workflows/pr-title.yml
  .github/workflows/release.yml
Labels: feature

#452 fix: release config name
  .github/workflows/release.yml
Labels: fix

#453 fix: use correct image name for release
  .github/workflows/release.yml
Labels: fix

#460 feat: Adding 'Created_At' column, defaulting to false
  README.md
  auth.py
  classes.py
  config.py
  issue_metrics.py
  markdown_writer.py
  test_config.py
Labels: feature

#462 fix: use correct created_at issue api attribute
  issue_metrics.py
Labels: fix, release

#466 chore: update workflows
  .github/release-drafter.yml
  .github/workflows/auto-labeler.yml
  .github/workflows/pr-title.yml
  .github/workflows/release.yml
Labels: maintenance, release
